# Base configs
baseurl: "https://hiaslhoam.github.io/photography/"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Matthias"
subtitle: ""
author: "Matthias Heim"
header:
  title: "Photography"
  subtitle: "by Matthias"
footer:
  name: "Hey there, my name is Matthias"
  bio: "Stroll around to see a few of the pictures I took. "
  github: 'Thanks to the awesome Ram Patra for this template. Want a website like this for yourself for free? Just <a href="https://github.com/ramswaroop/photography">fork this repo on github</a> ;)'
web_design: "Ram Patra/AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"},{"tag": "DateTimeOriginal", "icon": "calendar"}]'
social_urls:
  twitter: ""
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: ""
